-- Your SQL goes here
CREATE TABLE stocks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    avg_volume decimal NOT NULL DEFAULT 0,
    changes_percentage decimal NOT NULL DEFAULT 0,
    change decimal NOT NULL DEFAULT 0,
    day_low decimal NOT NULL DEFAULT 0,
    day_high decimal NOT NULL DEFAULT 0,
    description text NOT NULL DEFAULT '',
    eps decimal NOT NULL DEFAULT 0,
    exchange varchar(255) NOT NULL DEFAULT '',
    exchange_short_name varchar(255) NOT NULL DEFAULT '',
    ipo_date date NULL DEFAULT NULL,
    is_etf BOOLEAN NOT NULL DEFAULT FALSE,
    last_dividend decimal NOT NULL DEFAULT 0,
    market_cap decimal NOT NULL DEFAULT 0,
    name varchar(255) NOT NULL DEFAULT '',
    open decimal NOT NULL DEFAULT 0,
    previous_close decimal NOT NULL DEFAULT 0,
    price decimal NOT NULL DEFAULT 0,
    price_avg50 decimal NOT NULL DEFAULT 0,
    price_avg200 decimal NOT NULL DEFAULT 0,
    symbol varchar(255) NOT NULL DEFAULT '',
    volume decimal NOT NULL DEFAULT 0,
    website varchar(255) NOT NULL DEFAULT '',
    year_high decimal NOT NULL DEFAULT 0,
    year_low decimal NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
